const mappingItems = [
  { key: "roka", value: 1 },
  { key: "iceberg", value: 2 },
  { key: "sogan", value: 3 },
  { key: "sarimsak", value: 4 },
  { key: "patates", value: 5 },
  { key: "domates", value: 6 },
  { key: "brokoli", value: 7 },
  { key: "bruksel", value: 8 },
  { key: "limon", value: 9 },
  { key: "portakal", value: 10 },
  { key: "cilek", value: 11 },
  { key: "elma", value: 12 },
  { key: "uzum", value: 13 },
  { key: "avokado", value: 14 },
  { key: "meyve suyu", value: 15 },
  { key: "susi", value: 16 },
  { key: "cikolota", value: 17 },
  { key: "jelibon", value: 18 },
  { key: "sakiz", value: 19 },
  { key: "baharat", value: 20 },
  { key: "yag", value: 21 },
  { key: "pirinc", value: 22 },
  { key: "kitir ekmek", value: 23 },
  { key: "sehriye", value: 24 },
  { key: "misir", value: 25 },
  { key: "konserve", value: 26 },
  { key: "et", value: 27 },
  { key: "tavuk", value: 28 },
  { key: "peynir", value: 29 },
  { key: "sucuk", value: 30 },
  { key: "sut", value: 31 },
  { key: "yogurt", value: 32 },
  { key: "yumurta", value: 33 },
  { key: "ekmek", value: 34 },
  { key: "deterjan", value: 35 },
  { key: "pecete", value: 36 },
  { key: "tuvalet kagidi", value: 37 },
  { key: "deodorant", value: 38 },
  { key: "sampuan", value: 39 },
  { key: "el sabunu", value: 40 },
  { key: "soda", value: 41 },
  { key: "cola", value: 42 },
  { key: "kizartma patates", value: 43 },
  { key: "ton baligi", value: 44 },
  { key: "corba", value: 45 },
  { key: "sarap", value: 46 },
  { key: "jager", value: 47 },
  { key: "punkte", value: 48 },
];

export default mappingItems;
